import mongoose, { Document, Schema } from 'mongoose';

export type RecordCategory =
  | 'prescription'
  | 'scanning'
  | 'lab_report'
  | 'discharge_summary'
  | 'vaccination'
  | 'other';

export interface IMedication {
  medicineName: string;
  dosage?: string;
  frequency: string; // e.g. "Twice daily (1-0-1)"
  duration: string; // e.g. "7 Days"
  instructions: string; // e.g. "After food"
}

export interface IHealthRecord extends Document {
  patientUserId: mongoose.Types.ObjectId;
  patientName: string;
  title: string;
  category: RecordCategory;
  recordDate: string; // YYYY-MM-DD
  doctorName?: string;
  hospitalName?: string;
  fileUrl?: string;
  fileName?: string;
  fileType?: string; // e.g. 'pdf', 'image', 'document'
  fileSize?: string;
  description?: string;
  medications?: IMedication[];
  appointmentId?: mongoose.Types.ObjectId;
  isAutoGenerated?: boolean;
  tags?: string[];
  createdAt: Date;
  updatedAt: Date;
}

const HealthRecordSchema = new Schema<IHealthRecord>(
  {
    patientUserId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    patientName: {
      type: String,
      required: true,
      trim: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    category: {
      type: String,
      enum: ['prescription', 'scanning', 'lab_report', 'discharge_summary', 'vaccination', 'other'],
      default: 'other',
    },
    recordDate: {
      type: String,
      required: true,
      default: () => new Date().toISOString().split('T')[0],
    },
    doctorName: {
      type: String,
      default: '',
    },
    hospitalName: {
      type: String,
      default: '',
    },
    fileUrl: {
      type: String,
      default: '',
    },
    fileName: {
      type: String,
      default: '',
    },
    fileType: {
      type: String,
      default: 'document',
    },
    fileSize: {
      type: String,
      default: '',
    },
    description: {
      type: String,
      default: '',
    },
    medications: [
      {
        medicineName: { type: String, required: true },
        dosage: { type: String, default: '' },
        frequency: { type: String, default: 'Twice daily (1-0-1)' },
        duration: { type: String, default: '5 Days' },
        instructions: { type: String, default: 'After food' },
      },
    ],
    appointmentId: {
      type: Schema.Types.ObjectId,
      ref: 'Appointment',
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    tags: {
      type: [String],
      default: [],
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model<IHealthRecord>('HealthRecord', HealthRecordSchema);
