import { Response } from 'express';
import HealthRecord from '../models/HealthRecord';
import Appointment from '../models/Appointment';
import { AuthRequest } from '../middleware/auth';

/**
 * Automatically sync any appointments with prescriptions into HealthRecords for the patient
 */
const syncAppointmentPrescriptions = async (patientUserId: any, patientName: string) => {
  try {
    const prescribedAppointments = await Appointment.find({
      patientUserId,
      $or: [
        { prescription: { $exists: true, $ne: '' } },
        { 'medications.0': { $exists: true } },
      ],
    });

    for (const app of prescribedAppointments) {
      const existing = await HealthRecord.findOne({
        patientUserId,
        appointmentId: app._id,
      });

      const hasMeds = Array.isArray(app.medications) && app.medications.length > 0;
      const hasPrescription = app.prescription && app.prescription.trim().length > 0;

      if (!existing && (hasMeds || hasPrescription)) {
        await HealthRecord.create({
          patientUserId,
          patientName: patientName || app.patientName,
          title: `Prescription - ${app.doctorSpecialty} Consultation`,
          category: 'prescription',
          recordDate: app.appointmentDate,
          doctorName: app.doctorName,
          hospitalName: app.hospitalName || 'Independent Clinic',
          description: app.prescription || '',
          medications: app.medications || [],
          appointmentId: app._id,
          isAutoGenerated: true,
          fileName: `Prescription_${app.doctorName.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`,
          fileType: 'pdf',
          fileSize: '1.2 MB',
          tags: ['Doctor Prescription', app.doctorSpecialty, app.type === 'video' ? 'Telehealth' : 'In-Person'],
        });
      } else if (existing) {
        // Update prescription text & medications if changed by doctor
        existing.description = app.prescription || '';
        if (hasMeds) existing.medications = app.medications;
        existing.recordDate = app.appointmentDate;
        existing.doctorName = app.doctorName;
        existing.hospitalName = app.hospitalName;
        await existing.save();
      }
    }
  } catch (error) {
    console.error('Error syncing appointment prescriptions:', error);
  }
};

/**
 * Get all health records for the authenticated patient
 */
export const getMyRecords = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.user) {
      res.status(401).json({ success: false, message: 'Authentication required' });
      return;
    }

    // Auto-sync prescriptions from appointments
    await syncAppointmentPrescriptions(req.user._id, req.user.name);

    const { category, search, sort } = req.query;

    const query: any = { patientUserId: req.user._id };

    if (category && category !== 'all') {
      query.category = category;
    }

    if (search && typeof search === 'string' && search.trim()) {
      const regex = new RegExp(search.trim(), 'i');
      query.$or = [
        { title: regex },
        { doctorName: regex },
        { hospitalName: regex },
        { description: regex },
        { tags: { $in: [regex] } },
      ];
    }

    const sortOption: any = sort === 'oldest' ? { recordDate: 1, createdAt: 1 } : { recordDate: -1, createdAt: -1 };

    const records = await HealthRecord.find(query).sort(sortOption);

    // Summary counts by category
    const allRecords = await HealthRecord.find({ patientUserId: req.user._id });
    const counts = {
      total: allRecords.length,
      prescription: allRecords.filter((r) => r.category === 'prescription').length,
      scanning: allRecords.filter((r) => r.category === 'scanning').length,
      lab_report: allRecords.filter((r) => r.category === 'lab_report').length,
      discharge_summary: allRecords.filter((r) => r.category === 'discharge_summary').length,
      other: allRecords.filter((r) => !['prescription', 'scanning', 'lab_report', 'discharge_summary'].includes(r.category)).length,
    };

    res.status(200).json({
      success: true,
      count: records.length,
      counts,
      records,
    });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message || 'Failed to fetch health records' });
  }
};

/**
 * Create/Upload a new health record
 */
export const createRecord = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.user) {
      res.status(401).json({ success: false, message: 'Authentication required' });
      return;
    }

    const {
      title,
      category,
      recordDate,
      doctorName,
      hospitalName,
      fileUrl,
      fileName,
      fileType,
      fileSize,
      description,
      medications,
      tags,
    } = req.body;

    if (!title || !title.trim()) {
      res.status(400).json({ success: false, message: 'Record title is required' });
      return;
    }

    const record = await HealthRecord.create({
      patientUserId: req.user._id,
      patientName: req.user.name,
      title: title.trim(),
      category: category || 'other',
      recordDate: recordDate || new Date().toISOString().split('T')[0],
      doctorName: doctorName ? doctorName.trim() : '',
      hospitalName: hospitalName ? hospitalName.trim() : '',
      fileUrl: fileUrl || '',
      fileName: fileName || (title.replace(/[^a-zA-Z0-9]/g, '_') + '.pdf'),
      fileType: fileType || 'document',
      fileSize: fileSize || '1.5 MB',
      description: description ? description.trim() : '',
      medications: Array.isArray(medications) ? medications : [],
      tags: Array.isArray(tags) ? tags : typeof tags === 'string' ? tags.split(',').map((t: string) => t.trim()) : [],
      isAutoGenerated: false,
    });

    res.status(201).json({
      success: true,
      message: 'Health record uploaded successfully!',
      record,
    });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message || 'Failed to create health record' });
  }
};

/**
 * Get record by ID
 */
export const getRecordById = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.user) {
      res.status(401).json({ success: false, message: 'Authentication required' });
      return;
    }

    const { id } = req.params;
    const record = await HealthRecord.findById(id);

    if (!record) {
      res.status(404).json({ success: false, message: 'Health record not found' });
      return;
    }

    // Ensure only the owner or an affiliated doctor can access
    if (record.patientUserId.toString() !== req.user._id.toString() && req.user.role !== 'doctor') {
      res.status(403).json({ success: false, message: 'Not authorized to view this health record' });
      return;
    }

    res.status(200).json({
      success: true,
      record,
    });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message || 'Failed to fetch record' });
  }
};

/**
 * Update record
 */
export const updateRecord = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.user) {
      res.status(401).json({ success: false, message: 'Authentication required' });
      return;
    }

    const { id } = req.params;
    const record = await HealthRecord.findById(id);

    if (!record) {
      res.status(404).json({ success: false, message: 'Health record not found' });
      return;
    }

    if (record.patientUserId.toString() !== req.user._id.toString()) {
      res.status(403).json({ success: false, message: 'Not authorized to modify this record' });
      return;
    }

    const {
      title,
      category,
      recordDate,
      doctorName,
      hospitalName,
      fileUrl,
      fileName,
      fileType,
      fileSize,
      description,
      medications,
      tags,
    } = req.body;

    if (title !== undefined) record.title = title.trim();
    if (category !== undefined) record.category = category;
    if (recordDate !== undefined) record.recordDate = recordDate;
    if (doctorName !== undefined) record.doctorName = doctorName.trim();
    if (hospitalName !== undefined) record.hospitalName = hospitalName.trim();
    if (fileUrl !== undefined) record.fileUrl = fileUrl;
    if (fileName !== undefined) record.fileName = fileName;
    if (fileType !== undefined) record.fileType = fileType;
    if (fileSize !== undefined) record.fileSize = fileSize;
    if (description !== undefined) record.description = description.trim();
    if (medications !== undefined) record.medications = Array.isArray(medications) ? medications : [];
    if (tags !== undefined) {
      record.tags = Array.isArray(tags) ? tags : typeof tags === 'string' ? tags.split(',').map((t: string) => t.trim()) : [];
    }

    await record.save();

    res.status(200).json({
      success: true,
      message: 'Health record updated successfully',
      record,
    });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message || 'Failed to update record' });
  }
};

/**
 * Delete record
 */
export const deleteRecord = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.user) {
      res.status(401).json({ success: false, message: 'Authentication required' });
      return;
    }

    const { id } = req.params;
    const record = await HealthRecord.findById(id);

    if (!record) {
      res.status(404).json({ success: false, message: 'Health record not found' });
      return;
    }

    if (record.patientUserId.toString() !== req.user._id.toString()) {
      res.status(403).json({ success: false, message: 'Not authorized to delete this record' });
      return;
    }

    await HealthRecord.findByIdAndDelete(id);

    res.status(200).json({
      success: true,
      message: 'Health record deleted successfully',
    });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message || 'Failed to delete record' });
  }
};
